# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2

      # npm init and build vuepress
      - name: npm init & vuepress build
        run: |
          npm install
          npm run build
          
      # github settings
      - name: git settings actions env
        run: |
          git config --global user.name "Re1one"
          git config --global user.email j901207@gmail.com
          git config --global init.defaultBranch master

      # Runs a set of commands using the runners shell
      - name: create new commit and deploy gh-pages
        run: |
          cd docs/.vuepress/dist
          git init
          git remote add origin https://Reone1:${{secrets.GITHUB_TOKEN}}@github.com/Reone1/uoM.git
          git add .
          git commit -m "deploy"
          git push -f origin master:gh-pages
          
